'use strict';
const fs=require('node:fs');
const path=require('node:path');
const {DatabaseSync}=require('node:sqlite');
const {GEM_SET,GEAR,EQUIPMENT_SLOTS,STARTER_GEM_SET}=require('./catalog.cjs');
const {hashToken}=require('./security.cjs');

function createDb(dbPath=':memory:'){
  if(dbPath!==':memory:')fs.mkdirSync(path.dirname(dbPath),{recursive:true});
  const db=new DatabaseSync(dbPath,{open:true,timeout:5000});
  db.exec([
    'PRAGMA foreign_keys=ON;','PRAGMA journal_mode=WAL;','PRAGMA synchronous=NORMAL;','PRAGMA trusted_schema=OFF;',
    'CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,username_norm TEXT NOT NULL UNIQUE,username_display TEXT NOT NULL,password_hash TEXT NOT NULL,created_at INTEGER NOT NULL,failed_logins INTEGER NOT NULL DEFAULT 0,locked_until INTEGER NOT NULL DEFAULT 0) STRICT;',
    'CREATE TABLE IF NOT EXISTS profiles(user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,level INTEGER NOT NULL DEFAULT 1 CHECK(level>=1),xp INTEGER NOT NULL DEFAULT 0 CHECK(xp>=0),gold INTEGER NOT NULL DEFAULT 0 CHECK(gold>=0),created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL) STRICT;',
    "CREATE TABLE IF NOT EXISTS inventory(user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,item_id TEXT NOT NULL,kind TEXT NOT NULL CHECK(kind IN ('gem','gear')),qty INTEGER NOT NULL DEFAULT 1 CHECK(qty>=0),PRIMARY KEY(user_id,item_id)) STRICT;",
    'CREATE TABLE IF NOT EXISTS sack_slots(user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,slot INTEGER NOT NULL CHECK(slot BETWEEN 0 AND 4),gem_id TEXT NOT NULL,PRIMARY KEY(user_id,slot),UNIQUE(user_id,gem_id)) STRICT;',
    'CREATE TABLE IF NOT EXISTS equipment_slots(user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,slot TEXT NOT NULL,item_id TEXT,PRIMARY KEY(user_id,slot)) STRICT;',
    'CREATE TABLE IF NOT EXISTS starter_choices(user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,gem_id TEXT NOT NULL,chosen_at INTEGER NOT NULL) STRICT;',
    'CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,last_seen_at INTEGER NOT NULL,revoked_at INTEGER) STRICT;',
    'CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);','CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON sessions(expires_at);',
    "CREATE TABLE IF NOT EXISTS audit_events(id INTEGER PRIMARY KEY,user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,type TEXT NOT NULL,detail TEXT NOT NULL DEFAULT '',created_at INTEGER NOT NULL) STRICT;"
  ].join('\n'));
  return db;
}
function transaction(db,fn){db.exec('BEGIN IMMEDIATE');try{const value=fn();db.exec('COMMIT');return value}catch(error){try{db.exec('ROLLBACK')}catch{}throw error}}
function audit(db,userId,type,detail=''){db.prepare('INSERT INTO audit_events(user_id,type,detail,created_at) VALUES(?,?,?,?)').run(userId??null,type,String(detail).slice(0,500),Date.now())}
function seedAccount(db,{usernameNorm,usernameDisplay,passwordHash}){return transaction(db,()=>{const now=Date.now(),result=db.prepare('INSERT INTO users(username_norm,username_display,password_hash,created_at) VALUES(?,?,?,?)').run(usernameNorm,usernameDisplay,passwordHash,now),userId=Number(result.lastInsertRowid);db.prepare('INSERT INTO profiles(user_id,level,xp,gold,created_at,updated_at) VALUES(?,1,0,0,?,?)').run(userId,now,now);const gear=db.prepare('INSERT INTO equipment_slots(user_id,slot,item_id) VALUES(?,?,NULL)');for(const slot of Object.keys(EQUIPMENT_SLOTS))gear.run(userId,slot);audit(db,userId,'account_created_blank');return userId})}
function userByName(db,usernameNorm){return db.prepare('SELECT * FROM users WHERE username_norm=?').get(usernameNorm)||null}
function accountSnapshot(db,userId){const user=db.prepare('SELECT id,username_display,created_at FROM users WHERE id=?').get(userId);if(!user)return null;const profile=db.prepare('SELECT level,xp,gold,created_at,updated_at FROM profiles WHERE user_id=?').get(userId),inventory=db.prepare('SELECT item_id FROM inventory WHERE user_id=? AND qty>0 ORDER BY item_id').all(userId).map(r=>r.item_id),sack=Array(5).fill(null),equipment=Object.fromEntries(db.prepare('SELECT slot,item_id FROM equipment_slots WHERE user_id=? ORDER BY slot').all(userId).map(r=>[r.slot,r.item_id])),starter=db.prepare('SELECT gem_id,chosen_at FROM starter_choices WHERE user_id=?').get(userId)||null;for(const row of db.prepare('SELECT slot,gem_id FROM sack_slots WHERE user_id=? ORDER BY slot').all(userId))sack[row.slot]=row.gem_id;return {user:{id:user.id,username:user.username_display,createdAt:user.created_at},profile,sack,equipment,inventory,starter:starter?{gemId:starter.gem_id,chosenAt:starter.chosen_at}:null,needsStarter:!starter&&inventory.length===0}}
function owns(db,userId,itemId){return !!db.prepare('SELECT 1 ok FROM inventory WHERE user_id=? AND item_id=? AND qty>0').get(userId,itemId)}
function updateSack(db,userId,sack){if(!Array.isArray(sack)||sack.length!==5)throw Object.assign(new Error('invalid_sack'),{status:400});const equipped=sack.filter(Boolean);if(equipped.length<1||new Set(equipped).size!==equipped.length||!equipped.every(id=>GEM_SET.has(id)))throw Object.assign(new Error('invalid_sack'),{status:400});if(!equipped.every(id=>owns(db,userId,id)))throw Object.assign(new Error('unowned_item'),{status:403});transaction(db,()=>{db.prepare('DELETE FROM sack_slots WHERE user_id=?').run(userId);const stmt=db.prepare('INSERT INTO sack_slots(user_id,slot,gem_id) VALUES(?,?,?)');sack.forEach((gemId,slot)=>{if(gemId)stmt.run(userId,slot,gemId)});audit(db,userId,'sack_updated',equipped.join(','))})}
function chooseStarter(db,userId,gemId){if(!STARTER_GEM_SET.has(gemId))throw Object.assign(new Error('invalid_starter'),{status:400});return transaction(db,()=>{if(db.prepare('SELECT 1 ok FROM starter_choices WHERE user_id=?').get(userId))throw Object.assign(new Error('starter_already_chosen'),{status:409});if(db.prepare('SELECT 1 ok FROM inventory WHERE user_id=? AND qty>0').get(userId))throw Object.assign(new Error('starter_state_invalid'),{status:409});const now=Date.now();db.prepare("INSERT INTO inventory(user_id,item_id,kind,qty) VALUES(?,?,'gem',1)").run(userId,gemId);db.prepare('INSERT INTO sack_slots(user_id,slot,gem_id) VALUES(?,0,?)').run(userId,gemId);db.prepare('INSERT INTO starter_choices(user_id,gem_id,chosen_at) VALUES(?,?,?)').run(userId,gemId,now);audit(db,userId,'starter_chosen',gemId)})}
function updateEquipment(db,userId,equipment){if(!equipment||typeof equipment!=='object'||Array.isArray(equipment))throw Object.assign(new Error('invalid_equipment'),{status:400});const slots=Object.keys(EQUIPMENT_SLOTS);if(Object.keys(equipment).some(k=>!slots.includes(k)))throw Object.assign(new Error('invalid_equipment'),{status:400});const used=new Set();for(const slot of slots){const itemId=equipment[slot]??null;if(itemId===null)continue;const gear=GEAR[itemId];if(!gear||gear.slot!==EQUIPMENT_SLOTS[slot])throw Object.assign(new Error('wrong_slot'),{status:400});if(used.has(itemId))throw Object.assign(new Error('duplicate_physical_item'),{status:400});if(!owns(db,userId,itemId))throw Object.assign(new Error('unowned_item'),{status:403});used.add(itemId)}transaction(db,()=>{const stmt=db.prepare('UPDATE equipment_slots SET item_id=? WHERE user_id=? AND slot=?');for(const slot of slots)stmt.run(equipment[slot]??null,userId,slot);audit(db,userId,'equipment_updated')})}
function createSession(db,userId,token,ttlMs){const now=Date.now();db.prepare('INSERT INTO sessions(token_hash,user_id,created_at,expires_at,last_seen_at) VALUES(?,?,?,?,?)').run(hashToken(token),userId,now,now+ttlMs,now)}
function sessionUser(db,token){if(!token)return null;const now=Date.now(),hash=hashToken(token),row=db.prepare('SELECT s.token_hash,s.user_id,s.expires_at,s.revoked_at,u.username_display FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=?').get(hash);if(!row||row.revoked_at||row.expires_at<=now)return null;db.prepare('UPDATE sessions SET last_seen_at=? WHERE token_hash=?').run(now,hash);return {id:row.user_id,username:row.username_display,tokenHash:hash}}
function revokeSession(db,token){if(token)db.prepare('UPDATE sessions SET revoked_at=? WHERE token_hash=? AND revoked_at IS NULL').run(Date.now(),hashToken(token))}
function cleanupSessions(db){db.prepare('DELETE FROM sessions WHERE expires_at<? OR revoked_at IS NOT NULL').run(Date.now())}
module.exports={createDb,transaction,audit,seedAccount,userByName,accountSnapshot,updateSack,updateEquipment,chooseStarter,createSession,sessionUser,revokeSession,cleanupSessions};
